url: https://lalovic.io
baseurl: ""

# Meta
title: Marko Lalovic
author: Marko Lalovic
github_username: markolalovic
description: Marko Lalovic's homepage.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

sass:
  quiet_deps: true

remote_theme: pages-themes/midnight@v0.2.0